# Site settings
title: "Harshith's Archive"
description: "Personal blog and thoughts"
url: "https://harshithsarchive.github.io"
baseurl: ""

# Blog settings
paginate: 15
Blog: "/blog"

# Tracker
analytics:

# Comments
disqus-shortname:

# Build settings
markdown: kramdown
theme: harshiths-archive
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/