# Site settings
title: "harshith's archive"
description: "personal blog and thoughts"
url: "https://harshithsarchive.github.io"
baseurl: ""

# Blog settings
Blog: "/blog/"

# Navigation links
links:
  About: "/about/"

# Special links (external)
special_links: []

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
  my_tags:
    output: true
    permalink: /tagged/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - jekyllBear.gemspec
  - vendor/

# Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false